// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RINHABACKEND.Data;

#nullable disable

namespace Rinha.Migrations
{
    [DbContext(typeof(Databasecontext))]
    [Migration("20240220234326_porraaa")]
    partial class porraaa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RINHABACKEND.Model.Saldo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data_extrato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Total")
                        .HasColumnType("integer");

                    b.Property<int>("limite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Saldos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data_extrato = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = -9098,
                            limite = 100000
                        },
                        new
                        {
                            Id = 2,
                            Data_extrato = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 1000,
                            limite = 80000
                        },
                        new
                        {
                            Id = 3,
                            Data_extrato = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 2000,
                            limite = 1000000
                        },
                        new
                        {
                            Id = 4,
                            Data_extrato = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 120,
                            limite = 10000000
                        },
                        new
                        {
                            Id = 5,
                            Data_extrato = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total = 3,
                            limite = 200
                        });
                });

            modelBuilder.Entity("RINHABACKEND.Model.Transacao", b =>
                {
                    b.Property<int>("transacaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("transacaoID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Realizada_em")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SaldoId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("transacaoID");

                    b.HasIndex("SaldoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("RINHABACKEND.Model.Transacao", b =>
                {
                    b.HasOne("RINHABACKEND.Model.Saldo", null)
                        .WithMany("UltimasTransacoes")
                        .HasForeignKey("SaldoId");
                });

            modelBuilder.Entity("RINHABACKEND.Model.Saldo", b =>
                {
                    b.Navigation("UltimasTransacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
